USE EDUTEC2
GO

--
-- CREACION DE INDICES NO AGRUPADOS ( NONCLUSTERED ) (LÓGICOS)
EXEC SP_HELPINDEX ALUMNO
GO
SELECT * FROM Alumno
GO
SELECT * FROM Alumno ORDER BY ApeAlumno
GO
DROP INDEX ALUMNO.APELLIDO
GO
CREATE NONCLUSTERED INDEX APELLIDO
	ON ALUMNO(ApeAlumno)
GO
EXEC SP_HELPINDEX ALUMNO
GO
SELECT * FROM Alumno
GO
SELECT * FROM Alumno ORDER BY ApeAlumno
GO

DROP INDEX ALUMNO.NOMBRE
GO
SELECT * FROM Alumno ORDER BY NomAlumno
GO

CREATE NONCLUSTERED INDEX Nombre
	ON ALUMNO(NomAlumno)
GO

EXEC SP_HELPINDEX ALUMNO
GO

SELECT * FROM Alumno ORDER BY NomAlumno
GO

--
--

EXEC SP_HELPINDEX PROFESOR
GO

CREATE CLUSTERED INDEX PKPROFESOR
	ON PROFESOR(IDProfesor)
GO

EXEC SP_HELPINDEX PROFESOR
GO

CREATE NONCLUSTERED INDEX APENOM
	ON PROFESOR(ApeProfesor,NomProfesor)
GO
EXEC SP_HELPINDEX PROFESOR
GO

CREATE NONCLUSTERED INDEX DIRAPE 
ON PROFESOR(DirProfesor,ApeProfesor)
GO

EXEC SP_HELPINDEX PROFESOR
GO

SELECT * FROM Profesor ORDER BY DirProfesor,ApeProfesor
GO

SELECT  DirProfesor,ApeProfesor FROM Profesor 
ORDER BY DirProfesor,ApeProfesor
GO

EXEC SP_HELPINDEX EMPLEADO
GO

CREATE CLUSTERED INDEX PKEMPLEADO
	ON EMPLEADO(IDEmpleado)
GO

EXEC SP_HELPINDEX EMPLEADO
GO

CREATE NONCLUSTERED INDEX APELLIDOEMP
	ON EMPLEADO(ApeEmpleado)
GO
EXEC SP_HELPINDEX EMPLEADO
GO

SELECT * FROM Empleado
GO

CREATE NONCLUSTERED INDEX CARGOAPE
	ON EMPLEADO(Cargo,ApeEmpleado)
GO
EXEC SP_HELPINDEX EMPLEADO
GO


-- CONSULTAS CUBIERTAS
SELECT Cargo,ApeEmpleado FROM EMPLEADO 
ORDER BY Cargo,ApeEmpleado
GO
-- LOS CAMPOS QUE SE CONSULTAN FORMAN EL INDICE

-- ELIMINANDO INDICES

-- PRIMERO LOS NO AGRUPADOS
EXEC SP_HELPINDEX EMPLEADO
GO
DROP INDEX EMPLEADO.APELLIDOEMP
GO
EXEC SP_HELPINDEX EMPLEADO
GO
DROP INDEX EMPLEADO.CARGOAPE
GO
EXEC SP_HELPINDEX EMPLEADO
GO
-- LUEGO EL AGRUPADO
DROP INDEX EMPLEADO.PKEMPLEADO
GO
EXEC SP_HELPINDEX EMPLEADO
GO
--

USE Northwind
GO

SELECT * FROM Products
GO
SP_HELP PRODUCTS
GO
EXEC SP_HELPINDEX PRODUCTS
GO
--Presentar una lista de Productos mostrando 
-- El codigo de la categoria, 
-- El código del Proveedor, y 
-- el nombre del Producto. 
-- En ese mismo orden de la manera mas rapida posible.


SELECT CategoryId,SupplierId,ProductName FROM Products
ORDER BY CategoryId,SupplierId,ProductName
GO
CREATE NONCLUSTERED INDEX CatProvNom
	ON Products(CategoryId,SupplierId,ProductName)
GO
sp_helpindex Products
go
SELECT CategoryId,SupplierId,ProductName FROM Products
ORDER BY CategoryId,SupplierId,ProductName
GO




