--=======================================================
--Curso:SQL 3 
--Tema:Tarea 1
--Alumno:Soto S,Eden Persi
--Profesor:Julio Enrique Flores Manco
--Fecha:17/03/2022 
--=======================================================

/*Definir 2 factores de llenado en cada por cada pagina de datos*/


--Northwind-----------------------------------------------
USE Northwind
GO
 --Tabla Orders 
SELECT * FROM Orders
GO

SP_HELPINDEX Orders
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK_Orders'
GO

CREATE UNIQUE CLUSTERED INDEX PK_Orders ON Orders(OrderID)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK_Orders'
GO

--Tabla Employees 
SELECT * FROM Employees
GO
SP_HELPINDEX Employees
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK_Employees'
GO

CREATE UNIQUE CLUSTERED INDEX PK_Employees ON Employees(EmployeeID)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK_Employees'
GO

--pubs-----------------------------------------------------------
USE pubs
GO
--Tabla authors 
SELECT * FROM authors
GO

SP_HELPINDEX authors
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'UPKCL_auidind'
GO

CREATE UNIQUE CLUSTERED INDEX UPKCL_auidind ON authors(au_id)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'UPKCL_auidind'
GO

--Tabla sales 
SELECT * FROM sales
GO

SP_HELPINDEX sales
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'UPKCL_sales'
GO

CREATE UNIQUE CLUSTERED INDEX UPKCL_sales ON sales(stor_id,ord_num,title_id)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'UPKCL_sales'
GO

--EduTec---------------------------------------------------------------
USE EduTec
GO
--Tabla Curso 
SELECT * FROM Profesor
GO

SP_HELPINDEX Profesor
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__Profesor__C377C3A109B49806'
GO

CREATE UNIQUE CLUSTERED INDEX PK__Profesor__C377C3A109B49806 ON Profesor(idProfesor)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__Profesor__C377C3A109B49806'
GO

--Tabla Tarifa 
SELECT * FROM Tarifa
GO

SP_HELPINDEX Tarifa
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__Tarifa__78F1A91DA818D934'
GO

CREATE UNIQUE CLUSTERED INDEX PK__Tarifa__78F1A91DA818D934 ON Tarifa(idTarifa)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__Tarifa__78F1A91DA818D934'
GO

--MarketPERU----------------------------------------------------------
USE MarketPERU
GO
--Tabla GUIA 
SELECT * FROM GUIA
GO

SP_HELPINDEX GUIA
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__GUIA__838CF14050812E7D'
GO

CREATE UNIQUE CLUSTERED INDEX PK__GUIA__838CF14050812E7D ON GUIA(idGuia)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__GUIA__838CF14050812E7D'
GO

--Tabla PROVEEDOR 
SELECT * FROM PROVEEDOR
GO

SP_HELPINDEX PROVEEDOR
GO
SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__PROVEEDO__E8B631AFAFE2202D'
GO

CREATE UNIQUE CLUSTERED INDEX PK__PROVEEDO__E8B631AFAFE2202D ON PROVEEDOR(idProveedor)
    WITH DROP_EXISTING,
	FILLFACTOR = 80
GO

SELECT NAME, ORIGFILLFACTOR
FROM SYSINDEXES WHERE NAME = 'PK__PROVEEDO__E8B631AFAFE2202D'
GO